FROM registry.gsc.wustl.edu/sleong/scib

RUN R -e "BiocManager::install(c('multtest','scRNAseq','SingleCellExperiment','BiocGenerics', 'DelayedArray','limma', 'S4Vectors','SummarizedExperiment','batchelor','DelayedMatrixStats'))"
